import express from 'express';
import { SemesterRegistrationControler } from './semesterRegistration.controller';
import { validateRequest } from '../../middlewares';
import { semesterRegistrationValidation } from './semesterRegistration.validation';
const router = express.Router();
router.get('/', SemesterRegistrationControler.getAllSemesterRegistrations);
router.get('/:semesterRegistrationId', SemesterRegistrationControler.getSingleSemesterRegistration);
router.post('/create-semester-registration', validateRequest(semesterRegistrationValidation.createSemesterRegistrationValidationSchema), SemesterRegistrationControler.createSemesterRegistration);
router.patch('/:semesterRegistrationId', validateRequest(semesterRegistrationValidation.updateSemesterRegistrationValidationSchema), SemesterRegistrationControler.updateSemesterRegistration);
export const SemesterRegistration = router;